version: '3.7'

services:

  db:
    image: postgres:13.2-alpine
    restart: always
    environment:
      POSTGRES_USER: iam
      POSTGRES_PASSWORD: example
      POSTGRES_DB: iam-service
    ports:
      - 5432:5432

  adminer:
    image: adminer:4.7
    restart: always
    ports:
      - 8080:8080